language: node_js
node_js:
  - 0.10
  - 0.11
before_install:
  - export NEO4J_PORT="7474"
  - sudo service neo4j stop || true
  - sleep 3
  - ./install_local_neo4j.bash $NEO4J_VERSION
  - ./lib/neo4j/bin/neo4j start || ( cat ./lib/neo4j/data/log/*.log && exit 1 )
env:
  - NEO4J_VERSION="1.8.2"
  - NEO4J_VERSION="1.9.4"
  - NEO4J_VERSION="2.0.0-M06"
